### ISSUE TITLE
Fatal Exception: java.lang.IndexOutOfBoundsException while toggling Expanded Items.

### ISSUE THREAD

**Issue by Nebneb** [grennis/ExpandableRecyclerView#23]
Hi there, 

First, thank you very much for your great library, it saves me a lot of time and it is really tough and stable !

However, I'm encountering an issue in production on version 0.9.3. I can't reproduce it on my side but perhaps this stack trace could help you ? The index of 4 is just an example, it apparently happen in many situations.

`Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
       at java.util.ArrayList.get(ArrayList.java:437)
       at com.innodroid.expandablerecycler.ExpandableRecyclerAdapter.isExpanded(ExpandableRecyclerAdapter.java:160)
       at com.innodroid.expandablerecycler.ExpandableRecyclerAdapter.toggleExpandedItems(ExpandableRecyclerAdapter.java:91)
       at com.innodroid.expandablerecycler.ExpandableRecyclerAdapter$HeaderViewHolder.handleClick(ExpandableRecyclerAdapter.java:78)
       at com.innodroid.expandablerecycler.ExpandableRecyclerAdapter$HeaderViewHolder$1.onClick(ExpandableRecyclerAdapter.java:72)
       at android.view.View.performClick(View.java:6312)
       at android.view.View$PerformClick.run(View.java:24811)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:171)
       at android.app.ActivityThread.main(ActivityThread.java:6649)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)`

There is no particular device affected by this issue, affecting all brands, on Android 5->8 during the last 30 days. 

Do you have any idea on why or how this could happen? 

Again, thank you for your great work, and in advance for your help :).

**Comment by grennis** [comment]
Are you able to reproduce this by clicking very fast on an item to repeatedly expand/collapse? I think this may be a timing issue.

**Comment by Nebneb** [comment]
Hi Grennis, thanks for your help !

I just tested it, and it doesn't crash when clicking very fast on one item, **but** it does crash when I click very fast on 2 items simultaneously, one of the items being the last of the list. Then I have the exact same stack trace.

**Comment by grennis** [comment]
I see, probably the fix is something like prevent/ignore clicks while toggling expanded items. I'm not if that would belong in the library or when I might be able to look into it though.

**Comment by Nebneb** [comment]
Yes, ignoring clicks while toggling is an easy workaround to avoid the crash so it's good enough for me, at least temporarily. Thank you very much for your help !
